version: '3.5'

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./.docker/app/dev.Dockerfile
    image: zcheck-app-service
    restart: always
    working_dir: /app
    volumes:
      - ./:/app:cached
    depends_on:
      - mysql
      - redis
    networks:
      - zcheck-network
    environment:
      APP_DEBUG: 'true'
      XDEBUG_MODE: coverage

  nginx:
    image: nginx:1.19.8-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./public:/app/public:cached
      - ./.docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/app/ssl:/etc/ssl:cached
      - ./.docker/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - zcheck-network

  mysql:
    image: mysql:5.7.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: zcheck
    volumes:
      - zcheck_data:/var/lib/mysql
    networks:
      - zcheck-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8181:80
    networks:
      - zcheck-network

  redis:
    image: redis:5.0.9-alpine
    restart: always
    networks:
      - zcheck-network
      
volumes:
  zcheck_data:
    driver: local

networks:
  zcheck-network:
    name: zcheck-network
    driver: bridge
