import CodeMirror from 'codemirror';
window.CodeMirror = CodeMirror;
import 'codemirror/addon/edit/matchbrackets';
import 'codemirror/mode/javascript/javascript.js';
import 'codemirror/mode/htmlmixed/htmlmixed.js';
import 'codemirror/mode/xml/xml.js';
import 'codemirror/mode/css/css.js';
import 'codemirror/mode/clike/clike.js';
import 'codemirror/mode/php/php.js';
import 'codemirror/mode/ruby/ruby.js';
import 'codemirror/mode/python/python';
import 'codemirror/mode/go/go';
import 'codemirror/addon/selection/active-line';
import 'codemirror/addon/edit/matchbrackets';
import 'codemirror/addon/comment/comment';
import 'codemirror/addon/edit/closebrackets';
